# Generated by Django 2.0.7 on 2018-07-12 02:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('token', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='token')),
                ('ip_address', models.GenericIPAddressField(default='127.0.0.1', verbose_name='ip address')),
                ('user_agent', models.CharField(max_length=256, verbose_name='user agent')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
        ),
    ]
